### ISSUE TITLE
TimeSpan overflowed because the duration is too long

### ISSUE THREAD

**Issue by hawe484** [DuncteBot/skybot-lavalink-plugin#10]
Loading a soundgasm.net track gives me the **TimeSpan overflowed because the duration is too long** exception

It seems like any track I load gives me this exception but this is one of them:
https://soundgasm.net/u/skearch/test-audio

**Comment by duncte123** [comment]
Thanks for the report, I'll have a look asap

**Comment by duncte123** [comment]
I cannot seem to reproduce this problem with version 1.4.0, could you provide me your lavalink version and your lavalink client version?

![](https://ioexception.at/hfnBRvo6Mc.png)

**Comment by hawe484** [comment]
I'm currently using the lavalink 3.5.1 and what do you mean by lavalink client?

**Comment by hawe484** [comment]
Alright. I found the problem, whenever I look for the track **Length.TotalSeconds** it seems like it can't be converted to double because it's too long. Only really happens to **soundgasm.net** tracks tho
![image](https://user-images.githubusercontent.com/48974576/190256025-7f92394e-d714-4f31-b972-4e10ff0d3629.png)

Using C# and my Modified [DSharpPlus](https://dsharpplus.github.io/articles/audio/lavalink/configuration.html)

**Comment by duncte123** [comment]
I would contact the author of that c# lib because that implementation is wrong. That should be a 64 bit long. Lavaplayer (dependency or lavalink) uses the max value of a long to indicate that the length of a track is unknown or when you're playing a livestream (soundgasm does not provide a duration when scraping). The timestamp is in miliseconds so a double is a weird thing to have either way
